language: minimal

before_script:
  - cd project

services:
  - docker

jobs:
  include:
    - stage: Build
      script:
        - docker-compose -f docker-compose-build.yaml build --parallel

    - stage: Tagging
      script:
        - docker tag udagram-api-feed stleye/udagram-api-feed:v1
        - docker tag udagram-api-user stleye/udagram-api-user:v1
        - docker tag udagram-frontend stleye/udagram-frontend:v1
        - docker tag udagram-reverseproxy stleye/udagram-reverseproxy:v1

    - stage: Push
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push stleye/udagram-api-feed:v1
        - docker push stleye/udagram-api-user:v1
        - docker push stleye/udagram-frontend:v1
        - docker push stleye/udagram-reverseproxy:v1
