## Assuming the .travis.yml file is in the project directory, and there is a separate sub-directory for each service
## Use either `docker-compose` or individual `docker build` commands
## Build
  - docker-compose -f project/docker-compose-build.yaml build --parallel
## Do similar for other three images

## Tagging
  - docker tag project/udagram-api-feed stleye/udagram-api-feed:v1
  - docker tag project/udagram-api-user stleye/udagram-api-user:v1
  - docker tag project/udagram-frontend stleye/udagram-frontend:v1
  - docker tag project/udagram-reverseproxy stleye/udagram-reverseproxy:v1
## Do similar for other three images```
```bash
## Push
## Assuming DOCKER_PASSWORD and DOCKER_USERNAME are set in the Travis repository settings
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push stleye/udagram-api-feed:v1
  - docker push stleye/udagram-api-user:v1
  - docker push stleye/udagram-frontend:v1
  - docker push stleye/udagram-reverseproxy:v1
## Do similar for other three images
